global:
  security:
    allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnamilegacy/kafka
  tag: 3.5.2-debian-11-r0

controller:
  replicaCount: 1

broker:
  replicaCount: 5

listeners:
  client:
    protocol: SASL_PLAINTEXT
  interbroker:
    protocol: SASL_PLAINTEXT
  controller:
    protocol: SASL_PLAINTEXT

sasl:
  enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN

volumePermissions:
  enabled: false
