apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homework-chart.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
data:
  file: |
    app=homework
    course=kubernetes
    topic=helm-templating
