apiVersion: v1
kind: Service
metadata:
  name: {{ include "homework-chart.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "homework-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "homework-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
