apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: otus
  namespace: argocd
spec:
  description: Otus Kubernetes homework project
  sourceRepos:
    - https://github.com/Kuber-2026-02OTUS/sonya-sh_repo.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: homework
    - server: https://kubernetes.default.svc
      namespace: homeworkhelm
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
